### ISSUE TITLE
Link failure: some assembly references cannot be resolved!!

### ISSUE THREAD

**Issue by isheanesu** [Azure/amqpnetlite#493] opened 2022-03-12 03:57 UTC
I am getting this error after deploying to an ESP32:

Resolving.
Link failure: some assembly references cannot be resolved!!

The program '[1] .NET nanoFramework application: Managed' has exited with code 0 (0x0).
Assembly: Amqp.nanoFramework (2.1.0.0) needs assembly 'mscorlib' (1.10.5.4)
Assembly: Amqp.nanoFramework (2.1.0.0) needs assembly 'nanoFramework.System.Collections' (1.2.0.3)
Assembly: Amqp.nanoFramework (2.1.0.0) needs assembly 'System.Net' (1.7.0.3)
Error: a3000000
Waiting for debug commands...

Below is my package.config

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AMQPNetLite.nanoFramework" version="2.4.4-preview.1" targetFramework="netnanoframework10" />
  <package id="nanoFramework.CoreLibrary" version="1.11.7" targetFramework="netnanoframework10" />
  <package id="nanoFramework.ResourceManager" version="1.1.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.Runtime.Events" version="1.10.0-preview.1" targetFramework="netnanoframework10" />
  <package id="nanoFramework.Runtime.Native" version="1.5.2" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Collections" version="1.3.0" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Device.WiFi" version="1.4.0-preview.1" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Math" version="1.4.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Net" version="1.8.0-preview.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Text" version="1.1.3-preview.4" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Threading" version="1.0.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.Windows.Devices.Gpio" version="1.5.4-preview.3" targetFramework="netnanoframework10" />
</packages>

**Comment by xinchen10** [comment] 2022-03-14 16:04
@josesimoes

**Comment by isheanesu** [comment] 2022-03-14 16:51
@josesimoes  here is my packages.config. My device is running on ESP32_PSRAM_REV0 

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AMQPNetLite.nanoFramework" version="2.4.4-preview.1" targetFramework="netnanoframework10" />
  <package id="nanoFramework.CoreLibrary" version="1.11.7" targetFramework="netnanoframework10" />
  <package id="nanoFramework.ResourceManager" version="1.1.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.Runtime.Events" version="1.10.0-preview.1" targetFramework="netnanoframework10" />
  <package id="nanoFramework.Runtime.Native" version="1.5.2" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Collections" version="1.3.0" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Device.WiFi" version="1.4.0-preview.1" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Math" version="1.4.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Net" version="1.8.0-preview.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Text" version="1.1.3-preview.4" targetFramework="netnanoframework10" />
  <package id="nanoFramework.System.Threading" version="1.0.3" targetFramework="netnanoframework10" />
  <package id="nanoFramework.Windows.Devices.Gpio" version="1.5.4-preview.3" targetFramework="netnanoframework10" />
</packages>

**Comment by josesimoes** [comment] 2022-03-14 18:47
You haven't mentioned the version that you're using, but I suspect this is caused by a wrong mix of preview and stable versions.

I've just submitted PR #494 with a general update on all nugets.
Following the merge I'll fire a new build at our pipeline and you'll be able to use it safely. Note that you will have to use the latest preview version of the firmware. NOT the stable one.

**Comment by isheanesu** [comment] 2022-03-14 19:41
Thanks @josesimoes I am using ESP32_REV0-1.7.4-preview.98.zip but will switch to a stable release and test if it works.

**Comment by isheanesu** [comment] 2022-03-16 02:52
Thanks. The program now compiles and uploads without errors. However it is not running. Its just stuck at the Ready status, but if I remove the AMQP package it starts running. Could this be an issue with the capabilities of the device?

System Information
HAL build info: nanoCLR running @ ESP32 built with ESP-IDF v4.4
  Target:   ESP32
  Platform: ESP32

Firmware build Info:
  Date:        Mar 15 2022
  Type:        MinSizeRel build, chip rev. >= 0, without support for PSRAM
  CLR Version: 1.7.4.101
  Compiler:    GNU ARM GCC v8.4.0

OEM Product codes (vendor, model, SKU): 0, 0, 0

Serial Numbers (module, system):
  00000000000000000000000000000000
  0000000000000000

Target capabilities:
  Has nanoBooter: NO
  IFU capable: NO
  Has proprietary bootloader: YES

AppDomains:

Assemblies:
  AMQP, 1.0.0.0
  Amqp.nanoFramework, 2.1.0.0
  System.Net.Http, 1.4.0.0
  nanoFramework.ResourceManager, 1.1.4.0
  System.IO.Streams, 1.0.0.0
  nanoFramework.System.Text, 1.1.3.0
  System.Math, 1.4.4.0

Native Assemblies:
  mscorlib v100.5.0.17, checksum 0x004CF1CE
  nanoFramework.Runtime.Native v100.0.9.0, checksum 0x109F6F22
  nanoFramework.Hardware.Esp32 v100.0.7.3, checksum 0xBE7FF253
  nanoFramework.Hardware.Esp32.Rmt v100.0.3.0, checksum 0x9A53BB44
  nanoFramework.Device.OneWire v100.0.4.0, checksum 0xB95C43B4
  nanoFramework.Networking.Sntp v100.0.4.4, checksum 0xE2D9BDED
  nanoFramework.ResourceManager v100.0.0.1, checksum 0xDCD7DF4D
  nanoFramework.System.Collections v100.0.1.0, checksum 0x2DC2B090
  nanoFramework.System.Text v100.0.0.1, checksum 0x8E6EB73D
  nanoFramework.Runtime.Events v100.0.8.0, checksum 0x0EAB00C9
  EventSink v1.0.0.0, checksum 0xF32F4C3E
  System.IO.FileSystem v1.0.0.0, checksum 0x3AB74021
  System.Math v100.0.5.4, checksum 0x46092CB1
  System.Net v100.1.4.1, checksum 0xA01012C3
  Windows.Devices.Adc v100.1.3.3, checksum 0xCA03579A
  System.Device.Adc v100.0.0.0, checksum 0xE5B80F0B
  System.Device.Dac v100.0.0.6, checksum 0x02B3E860
  System.Device.Gpio v100.1.0.4, checksum 0xB6D0ACC1
  Windows.Devices.Gpio v100.1.2.2, checksum 0xC41539BE
  Windows.Devices.I2c v100.2.0.2, checksum 0x79EDBF71
  System.Device.I2c v100.0.0.1, checksum 0xFA806D33
  Windows.Devices.Pwm v100.1.3.3, checksum 0xBA2E2251
  System.Device.Pwm v100.1.0.4, checksum 0xABF532C3
  Windows.Devices.SerialCommunication v100.1.1.2, checksum 0x34BAF06E
  System.IO.Ports v100.1.4.0, checksum 0xCB7C0ECA
  Windows.Devices.Spi v100.1.4.2, checksum 0x360239F1
  System.Device.Spi v100.1.1.0, checksum 0x3F6E2A7E
  System.Device.WiFi v100.0.6.3, checksum 0x5C9E06C4
  Windows.Storage v100.0.2.0, checksum 0x954A4192



++++++++++++++++++++++++++++++++
++        Memory Map          ++
++++++++++++++++++++++++++++++++
  Type     Start       Size
++++++++++++++++++++++++++++++++
  RAM   0x3ffe49ac  0x0001b000
  FLASH 0x00000000  0x00400000



+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++                   Flash Sector Map                        ++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  Region     Start      Blocks   Bytes/Block    Usage
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      0    0x00010000       1      0x1A0000     nanoCLR
      1    0x001B0000       1      0x1F0000     Deployment
      2    0x003C0000       1      0x040000     Configuration


+++++++++++++++++++++++++++++++++++++++++++++++++++
++              Storage Usage Map                ++
+++++++++++++++++++++++++++++++++++++++++++++++++++
  Start        Size (kB)           Usage
+++++++++++++++++++++++++++++++++++++++++++++++++++
  0x003C0000    0x040000 (256kB)    Configuration
  0x00010000    0x1A0000 (1664kB)   nanoCLR
  0x001B0000    0x1F0000 (1984kB)   Deployment



Deployment Map
Empty

**Comment by josesimoes** [comment] 2022-03-16 07:57
> Thanks. The program now compiles and uploads without errors. However it is not running. Its just stuck at the Ready status, but if I remove the AMQP package it starts running. Could this be an issue with the capabilities of the device?

Need more details to understand why. The original issue has been solved, so I suggest you close this issue and head over to our [Discord server](https://discord.gg/gCyBu8T) so you can get help about this new issue, which is nanoFramework specific.

**Closed** 2022-03-16 10:40 UTC
