### ISSUE TITLE
CreateAsync throws unexpected exception

### ISSUE THREAD

**Issue by jjpepper** [Azure/amqpnetlite#283] opened 2018-07-06 03:20 UTC
Hi there, thanks for the great library.
Can someone please explain the rationale behind `ReceiveBufferAsync()` in Net/AsyncPump.cs throwing an `ObjectDisposedException` during a call to `CreateAsync()`.  It seems to be the wrong type of exception to throw and a better message could be used.  For example: `Unexpected end of receive network stream. Peer signalled more bytes were being sent than got sent.`

Please also document that an exception can be thrown on CreateAsync(). 

If possible, could you also give some insight for a likely cause of this?  I'm seeing it often, but when running the same code in 16 containers only one container fails in this way.

**Comment by xinchen10** [comment] 2018-07-06 23:06
When ReceiveAsync returns 0, the transport has been closed (graceful shutdown). If the application does not close the connection, the transport is closed by the remote peer. To the pump this is an error which needs to be propagated to the connection's OnIoException callback so the connection can be faulted. ObjectDisposedException was chosen to indicate that the transport is in closed state. 

Changing the exception type/message is possible but it does not solve the root cause - unstable socket connection. You may want to look into a network capture to understand why the tcp connection got closed for this container very often.

**Comment by jjpepper** [comment] 2018-07-06 23:11
The root cause has been understood, but not before spending some time
looking for an object being used after it was disposed. That’s what
ObjectDisposed exception means. It implies a programming error, not a valid
network state.  Please do use a different exception type and a clear
message.

**Comment by xinchen10** [comment] 2018-07-06 23:29
Would an OperationCancelledException with message 'The TcpTransport has been closed' help in your investigation? Just want to make sure we choose something that is helpful.

**Comment by jjpepper** [comment] 2018-07-06 23:58
Yep, sounds good.  Thanks!

**Closed** 2018-08-30 20:51 UTC
